[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
tokio = { version = "1.53.1", features = ["macros","rt-multi-thread"]}
axum = "0.8.9"
tower-http = "0.7.1"
serde = "1.0.229"
sqlx = { version = "0.8.6", features = ["postgres","uuid","time","runtime-tokio"]}
argon2 = "0.5"
uuid = { version = "1.26.1", features = ["v4", "serde"]}
axum-login = "0.18.0"
bollard = "0.21.1"
reqwest = { version = "0.13.5", features = ["rustls-tls"] }
zip = "8.6.0"
java-properties = "2.0.0"
craftping = "0.8.0"
thiserror = "2.0.21"
anyhow = "1.0.104"
testcontainers = "0.28.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tower-sessions = { version = "0.14.0", default-features = false, features = ["signed",] }
tower-sessions-sqlx-store = "0.15.0"
dotenv = "0.15.0"
